import { build } from 'esbuild';
import { writeFileSync } from 'node:fs';

const result = await build({
  entryPoints: ['src/runtime/index.ts'],
  bundle: true,
  format: 'iife',
  globalName: 'SavigRuntimeBundle',
  target: 'es2020',
  minify: false,
  legalComments: 'none',
  write: false,
});

const js = result.outputFiles[0].text;
const module = `// GENERATED by scripts/build-runtime.mjs — do not edit by hand.\n` +
  `export const RUNTIME_JS = ${JSON.stringify(js)};\n`;
writeFileSync('src/runtime/runtimeSource.generated.ts', module);
console.log(`Wrote runtimeSource.generated.ts (${js.length} bytes of runtime).`);
